POST http://localhost:3000/assets
Content-Type: application/json

{
  "name": "Amazon1",
  "symbol": "A21",
  "price": "1030",
  "image": "AMZxN.png"
}

###
GET  http://localhost:3000/assets

###
GET  http://localhost:3000/assets/A21

###

# @name createWallet
POST http://localhost:3000/wallet




###

GET http://localhost:3000/wallet

###

@walletId = {{createWallet.response.body._id}}
GET http://localhost:3000/wallet/{{walletId}}


